run:
  seed: 0
  out_root: outputs
  name: mnist-base-ensemble 

data:
  source: tf_keras
  dataset_name: mnist
  batch_size: 128
  val_split: 0.1

model:
  name: mlp
  width: [32, 32]
  num_classes: 10

quant:
  activation_total_bits: 4
  activation_int_bits: 2
  weight_total_bits: 4
  weight_int_bits: 1

train:
  epochs: 20
  optimizer: adam
  lr: 0.0003
  beta1: 0.9
  beta2: 0.999
  loss: sparse_ce
  metrics: [sparse_acc]

callbacks:
  early_stopping:
    enabled: true
    patience: 5
  checkpoint:
    enabled: true
    monitor: val/sparse_acc
  wandb:
    enabled: true 
    log_freq: epoch

ensemble:
  size: 4

wandb:
  enabled: true 
  project: qensemble
  group: mnist
  tags: ["mnist"]
