program: -m qensemble.main
name: cifar10_phase1_single
method: grid
metric:
  name: val/sparse_acc
  goal: maximize
parameters:
  ensemble.size:
    value: 1
  model.variant:
    values: [small, medium, large]
  quant.activation_total_bits:
    values: [2, 4, 6, 8]
  quant.activation_int_bits:
    value: 1
  quant.weight_total_bits:
    values: [2, 4, 6, 8]
  quant.weight_int_bits:
    value: 1
  run.seed:
    values: [0, 1, 2]
command:
  - ${env}
  - python
  - ${program}
  - --config
  - configs/cifar10/base.yaml
